name: weather_analytics
version: "1.0.0"
config-version: 2

profile: weather_analytics

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  weather_analytics:
    staging:
      +materialized: view    # light cleanup layer
    analytics:
      +materialized: table   # final tables used by the dashboard
